using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace FileUploader.ModelConfigurations
{
    public class ModelConfiguration : ModelConfigurationBase
    {
        //<suite-custom-code-autogenerated>
        protected ModelConfiguration()
        {

        }

        public ModelConfiguration(Guid id, double temperature, string? systemPrompt = null, string? topK = null, string? topP = null, string? repeatPenalty = null, string? contextLength = null, string? maxTokens = null)
            : base(id, temperature, systemPrompt, topK, topP, repeatPenalty, contextLength, maxTokens)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}