using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace FileUploader.ModelConfigurations
{
    public class ModelConfigurationManager : ModelConfigurationManagerBase
    {
        //<suite-custom-code-autogenerated>
        public ModelConfigurationManager(IModelConfigurationRepository modelConfigurationRepository)
            : base(modelConfigurationRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}