using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace FileUploader.ModelRegistrations
{
    public class ModelRegistrationManager : ModelRegistrationManagerBase
    {
        //<suite-custom-code-autogenerated>
        public ModelRegistrationManager(IModelRegistrationRepository modelRegistrationRepository)
            : base(modelRegistrationRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}