using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using FileUploader.Permissions;
using FileUploader.UploadFiles;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using FileUploader.Shared;

namespace FileUploader.UploadFiles
{
    public class UploadFilesAppService : UploadFilesAppServiceBase, IUploadFilesAppService
    {
        //<suite-custom-code-autogenerated>
        public UploadFilesAppService(IUploadFileRepository uploadFileRepository, UploadFileManager uploadFileManager, IDistributedCache<UploadFileExcelDownloadTokenCacheItem, string> excelDownloadTokenCache)
            : base(uploadFileRepository, uploadFileManager, excelDownloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}