using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace FileUploader.UploadFiles
{
    public class UploadFile : UploadFileBase
    {
        //<suite-custom-code-autogenerated>
        // protected UploadFile()
        // {

        // }

        public UploadFile(Guid id, string? fileName = null, string? filePath = null, string? fileType = null, string? fileSize = null)
            : base(id, fileName, filePath, fileType, fileSize)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}