using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace FileUploader.UploadFiles
{
    public class UploadFileManager : UploadFileManagerBase
    {
        //<suite-custom-code-autogenerated>
        public UploadFileManager(IUploadFileRepository uploadFileRepository)
            : base(uploadFileRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}