using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using FileUploader.Permissions;
using FileUploader.ModelTrainings;

namespace FileUploader.ModelTrainings
{
    public class ModelTrainingsAppService : ModelTrainingsAppServiceBase, IModelTrainingsAppService
    {
        //<suite-custom-code-autogenerated>
        public ModelTrainingsAppService(IModelTrainingRepository modelTrainingRepository, ModelTrainingManager modelTrainingManager)
            : base(modelTrainingRepository, modelTrainingManager)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}