using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace FileUploader.ModelTrainings
{
    public class ModelTrainingManager : ModelTrainingManagerBase
    {
        //<suite-custom-code-autogenerated>
        public ModelTrainingManager(IModelTrainingRepository modelTrainingRepository)
            : base(modelTrainingRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}