using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using FileUploader.Permissions;
using FileUploader.ModelRegistrations;

namespace FileUploader.ModelRegistrations
{
    public class ModelRegistrationsAppService : ModelRegistrationsAppServiceBase, IModelRegistrationsAppService
    {
        //<suite-custom-code-autogenerated>
        public ModelRegistrationsAppService(IModelRegistrationRepository modelRegistrationRepository, ModelRegistrationManager modelRegistrationManager)
            : base(modelRegistrationRepository, modelRegistrationManager)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}