using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using FileUploader.Permissions;
using FileUploader.ModelConfigurations;

namespace FileUploader.ModelConfigurations
{
    public class ModelConfigurationsAppService : ModelConfigurationsAppServiceBase, IModelConfigurationsAppService
    {
        //<suite-custom-code-autogenerated>
        public ModelConfigurationsAppService(IModelConfigurationRepository modelConfigurationRepository, ModelConfigurationManager modelConfigurationManager)
            : base(modelConfigurationRepository, modelConfigurationManager)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}