version: '3.8'

services:
  fileuploader-angular:
    image: mycompanyname/fileuploader-angular:latest
    container_name: fileuploader-angular
    build:
      context: ../../../
      dockerfile: angular/Dockerfile.local
    ports:
      - "4200:80"
    depends_on:
      - fileuploader-api
    volumes:
      - ./dynamic-env.json://usr/share/nginx/html/dynamic-env.json
    networks:
      - abp-network

  fileuploader-api:
    image: mycompanyname/fileuploader-api:latest
    container_name: fileuploader-api
    hostname: fileuploader-api
    build:
      context: ../../
      dockerfile: src/FileUploader.HttpApi.Host/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=82b8a672-746b-48ed-a8e2-edbf65db267d
      - App__SelfUrl=https://localhost:44354
      - App__AngularUrl=http://localhost:4200
      - App_CorsOrigins=http://localhost:4200
      - App__HealthCheckUrl=http://fileuploader-api/health-status
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__Authority=http://fileuploader-authserver
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=FileUploader;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
      - Redis__Configuration=redis
    ports:
      - "44354:443"
    depends_on:
      sql-server:
        condition: service_healthy
      redis:
        condition: service_healthy  
    restart: on-failure    
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network
  
  fileuploader-authserver:
    image: mycompanyname/fileuploader-authserver:latest
    container_name: fileuploader-authserver
    build:
      context: ../../
      dockerfile: src/FileUploader.AuthServer/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - App__SelfUrl=https://localhost:44334
      - App__CorsOrigins=http://localhost:4200,http://localhost:44307
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__Authority=https://localhost:44334/
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=82b8a672-746b-48ed-a8e2-edbf65db267d
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=FileUploader;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
      - Redis__Configuration=redis
    ports:
      - "44334:443"
    depends_on:
      sql-server:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network

  db-migrator:
    image: mycompanyname/fileuploader-db-migrator:latest
    container_name: db-migrator
    build:
      context: ../../
      dockerfile: src/FileUploader.DbMigrator/Dockerfile.local
    environment:
      - OpenIddict__Applications__FileUploader_App__RootUrl=http://localhost:4200
      - OpenIddict__Applications__FileUploader_Swagger__RootUrl=https://localhost:44354
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=FileUploader;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
      - Redis__Configuration=redis
    restart: on-failure
    depends_on:
      sql-server:
        condition: service_healthy
    networks:
      - abp-network    
  
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "myPassw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - abp-network
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S sql-server -U sa -P "myPassw0rd" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
  
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - abp-network  
    healthcheck:
      test: ["CMD", "redis-cli","ping"]      

volumes:
  sqldata:
    name: fileuploader_sqldata
networks:
  abp-network:
    name: fileuploader-network
    driver: bridge
