using FileUploader.ModelConfigurations;
using Xunit;

namespace FileUploader.EntityFrameworkCore.Applications.ModelConfigurations;

public class EfCoreModelConfigurationsAppServiceTests : ModelConfigurationsAppServiceTests<FileUploaderEntityFrameworkCoreTestModule>
{
}